name: Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Checkout du dépôt Git
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2: Connexion au Harbor Registry
      - name: Log in to Harbor
        run: echo "B4teau123!" | docker login harbor.kakor.ovh --username "ipi" --password-stdin

      # Étape 3:  Construction de l'image Docker
      - name: Build Docker image
        run: docker build -f Dockerfile -t harbor.kakor.ovh/ipi/groupe1:v1 .

      # Étape 4: Pousser l'image dans le registry
      - name: Push Docker image to Harbor
        run: docker push harbor.kakor.ovh/ipi/groupe1:v1

      - name: Install Trivy
        run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.40.0/trivy_0.40.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.40.0_Linux-64bit.deb

      - name: Scan Docker image with Trivy
        id: scan-image
        run: |
        trivy image — format json — output scan-results.json harbor.kakor.ovh/ipi/groupe1:v1