name: Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Checkout du dépôt Git
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2: Connexion au Harbor Registry
      - name: Log in to Harbor
        run: echo "B4teau123!" | docker login harbor.kakor.ovh --username "ipi" --password-stdin

      # Étape 3:  Construction de l'image Docker
      - name: Build Docker image
        run: docker build -f Dockerfile -t harbor.kakor.ovh/ipi/groupe1:v1 .

      # Étape 4: Pousser l'image dans le registry
      - name: Push Docker image to Harbor
        run: docker push harbor.kakor.ovh/ipi/groupe1:v1

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'harbor.kakor.ovh/ipi/groupe1:v1'
          format: 'json'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'MEDIUM'
        continue-on-error: true

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: https://api.openshift.kakor.ovh:6443
          openshift_token: sha256~Uar1QektwyCEHJZgst7yvfl48XSWPDNzUx5Of7L1GFk
          insecure_skip_tls_verify: true
          namespace: projet-gp-1

      - name: Deploy appli
        run: oc apply -f kubernetes-manifests/ -n projet-gp-1

      - name: Vérification que notre deploiement est OK
        run: |
          oc get deploy -n projet-gp-1 
          oc get services -n projet-gp-1
          oc get routes -n projet-gp-1

      - name: Vérification que l'application fonctionne
        run: curl -k https://python-gp-1.apps.openshift.kakor.ovh/livres
        continue-on-error: true